spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-cyym-dev


---

spring:
  profiles: test
  application:
    name: microservicecloud-config-cyym-test